export const dataMisProyectosDummy =[
    {
        id:'1',
        nombreProyecto: 'Proyecto1',
        idFinalidadProyecto: '1',
        idTipoProyecto: '3',
        idSubTipoProyecto:'7',
        estadoProyecto:'Activo',
        iconoProyecto: 'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/comida.png',
        finalidadProyecto: 'Hobby',
        tipoProyecto: 'App',
        subTipoProyecto: 'App Web',
        numeroEquipos: 0,
        fechaCreacionProyecto: '11-02-2025',
        completado: true
    },
    {
        id:'2',
        nombreProyecto: 'Proyecto2',
        idFinalidadProyecto: '1',
        idTipoProyecto: '3',
        idSubTipoProyecto:'7',
        estadoProyecto:'Suspendido',
        iconoProyecto: 'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/check.png',
        finalidadProyecto: 'Educativo',
        tipoProyecto: 'App',
        subTipoProyecto: 'App Movil',
        numeroEquipos: 0,
        fechaCreacionProyecto: '17-01-2025',
        completado: true
    },
    {
        id:'3',
        nombreProyecto: 'Proyecto3',
        idFinalidadProyecto: '1',
        idTipoProyecto: '3',
        idSubTipoProyecto:'7',
        estadoProyecto:'Suspendido',
        iconoProyecto: 'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/azure.png',
        finalidadProyecto: 'Hobby',
        tipoProyecto: 'Landing Page',
        subTipoProyecto: 'Landing Page',
        numeroEquipos: 0,
        fechaCreacionProyecto: '17-01-2025',
        completado: false
    },
    {
        id:'4',
        nombreProyecto: 'Proyecto4',
        idFinalidadProyecto: '1',
        idTipoProyecto: '3',
        idSubTipoProyecto:'7',
        estadoProyecto:'Activo',
        iconoProyecto: 'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/logoPrincipal.png',
        finalidadProyecto: 'Empresarial',
        tipoProyecto: 'App',
        subTipoProyecto: 'App Web',
        numeroEquipos: 0,
        fechaCreacionProyecto: '17-01-2025',
        completado: true
    },
    {
        id:'5',
        nombreProyecto: 'Proyecto5',
        idFinalidadProyecto: '1',
        idTipoProyecto: '3',
        idSubTipoProyecto:'7',
        estadoProyecto:'Eliminado',
        iconoProyecto: 'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/cloudflare2.png',
        finalidadProyecto: 'Hobby',
        tipoProyecto: 'App',
        subTipoProyecto: 'App Escritorio',
        numeroEquipos: 0,
        fechaCreacionProyecto: '15-02-2025',
        completado: true
    },
    {
        id:'6',
        nombreProyecto: 'Proyecto6',
        idFinalidadProyecto: '1',
        idTipoProyecto: '3',
        idSubTipoProyecto:'7',
        estadoProyecto:'Activo',
        iconoProyecto: 'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/pregunta.png',
        finalidadProyecto: 'Hobby',
        tipoProyecto: 'App',
        subTipoProyecto: 'App Escritorio',
        numeroEquipos: 0,
        fechaCreacionProyecto: '15-02-2025',
        completado: true
    },
    {
        id:'7',
        nombreProyecto: 'Proyecto7',
        idFinalidadProyecto: '1',
        idTipoProyecto: '3',
        idSubTipoProyecto:'7',
        estadoProyecto:'Eliminado',
        iconoProyecto: 'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/angular.png',
        finalidadProyecto: 'Hobby',
        tipoProyecto: 'App',
        subTipoProyecto: 'App Escritorio',
        numeroEquipos: 0,
        fechaCreacionProyecto: '15-02-2025',
        completado: true
    },
    // {
    //     id:'1',
    //     nombreProyecto: 'Proyecto1',
    //     iconoProyecto: proyectoIcono,
    //     tipoProyecto: 'App',
    //     subTipoProyecto: 'App Web',
    //     numeroEquipos: 2,
    //     fechaCreacionProyecto: '17-01-2025',
    //     completado: true
    // },
    // {
    //     id:'2',
    //     nombreProyecto: 'Proye2',
    //     iconoProyecto: proyectoIcono2,
    //     tipoProyecto: 'App',
    //     subTipoProyecto: 'App Movil',
    //     numeroEquipos: 5,
    //     fechaCreacionProyecto: '17-01-2025',
    //     completado: true
    // },
    // {
    //     id:'3',
    //     nombreProyecto: 'Proyecto 3',
    //     iconoProyecto: proyectoIcono3,
    //     tipoProyecto: 'Landing Page',
    //     subTipoProyecto: 'Landing Page',
    //     numeroEquipos: 4,
    //     fechaCreacionProyecto: '17-01-2025',
    //     completado: false
    // },
    // {
    //     id:'4',
    //     nombreProyecto: 'Pro4',
    //     iconoProyecto: proyectoIcono4,
    //     tipoProyecto: 'App',
    //     subTipoProyecto: 'App Web',
    //     numeroEquipos: 1,
    //     fechaCreacionProyecto: '17-01-2025',
    //     completado: true
    // },
    // {
    //     id:'5',
    //     nombreProyecto: 'Fucking 5',
    //     iconoProyecto: proyectoIcono5,
    //     tipoProyecto: 'App',
    //     subTipoProyecto: 'App Escritorio',
    //     numeroEquipos: 1,
    //     fechaCreacionProyecto: '15-02-2025',
    //     completado: true
    // },
    // {
    //     id:'1',
    //     nombreProyecto: 'Proyecto1',
    //     iconoProyecto: proyectoIcono,
    //     tipoProyecto: 'App',
    //     subTipoProyecto: 'App Web',
    //     numeroEquipos: 2,
    //     fechaCreacionProyecto: '17-01-2025',
    //     completado: true
    // },
    // {
    //     id:'2',
    //     nombreProyecto: 'Proye2',
    //     iconoProyecto: proyectoIcono2,
    //     tipoProyecto: 'App',
    //     subTipoProyecto: 'App Movil',
    //     numeroEquipos: 5,
    //     fechaCreacionProyecto: '17-01-2025',
    //     completado: true
    // },
    // {
    //     id:'3',
    //     nombreProyecto: 'Proyecto 3',
    //     iconoProyecto: proyectoIcono3,
    //     tipoProyecto: 'Landing Page',
    //     subTipoProyecto: 'Landing Page',
    //     numeroEquipos: 4,
    //     fechaCreacionProyecto: '17-01-2025',
    //     completado: false
    // },
    // {
    //     id:'4',
    //     nombreProyecto: 'Pro4',
    //     iconoProyecto: proyectoIcono4,
    //     tipoProyecto: 'App',
    //     subTipoProyecto: 'App Web',
    //     numeroEquipos: 1,
    //     fechaCreacionProyecto: '17-01-2025',
    //     completado: true
    // },
    // {
    //     id:'5',
    //     nombreProyecto: 'Fucking 5',
    //     iconoProyecto: proyectoIcono5,
    //     tipoProyecto: 'App',
    //     subTipoProyecto: 'App Escritorio',
    //     numeroEquipos: 1,
    //     fechaCreacionProyecto: '15-02-2025',
    //     completado: true
    // },
    
    
]