

export const dataMisContactos = [
    {
        id: '1',
        avatar: 'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/aws.png',
        cargo: 'Desarrollador Frontend',
        nombre: 'Juan',
        apellido: 'Pérez',
        trabajando: true,
        email: 'jorge@gmail.com',
        empresa: 'Roudev',
        telefono: '123456789',
        siguiendo: false,
        proyectos: ['Proyecto 1', 'Proyecto 2'],
        
    },
    {
        id: '2',
        avatar: 'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/azure.png',
        cargo: 'Desarrollador Frontend',
        nombre: 'Juan',
        apellido: 'Pérez',
        trabajando: true,
        email: 'jorge@gmail.com',
        empresa: 'Roudev',
        telefono: '123456789',
        siguiendo: false,
        proyectos: ['Proyecto 1', 'Proyecto 2'],
    },
    {
        id: '3',
        avatar: 'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/pregunta.png',
        cargo: 'Desarrollador Frontend',
        nombre: 'Juan',
        apellido: 'Pérez',
        trabajando: true,
        email: 'jorge@gmail.com',
        empresa: 'Roudev',
        telefono: '123456789',
        siguiendo: false,
        proyectos: ['Proyecto 1', 'Proyecto 2'],
    },
    {
        id: '4',
        avatar: 'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/check.png',
        cargo: 'Desarrollador Frontend',
        nombre: 'Juan',
        apellido: 'Pérez',
        trabajando: true,
        email: 'jorge@gmail.com',
        empresa: 'Roudev',
        telefono: '123456789',
        siguiendo: false,
        proyectos: ['Proyecto 1', 'Proyecto 2'],
    },
    {
        id: '5',
        avatar: 'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/comida.png',
        cargo: 'Desarrollador Frontend',
        nombre: 'Juan',
        apellido: 'Pérez',
        trabajando: true,
        email: 'jorge@gmail.com',
        empresa: 'Roudev',
        telefono: '123456789',
        siguiendo: false,
        proyectos: ['Proyecto 1', 'Proyecto 2'],
    },
    {
        id: '6',
        avatar: 'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/campana2.png',
        cargo: 'Desarrollador Frontend',
        nombre: 'Juan',
        apellido: 'Pérez',
        trabajando: true,
        email: 'jorge@gmail.com',
        empresa: 'Roudev',
        telefono: '123456789',
        siguiendo: false,
        proyectos: ['Proyecto 1', 'Proyecto 2'],
    },
    {
        id: '7',
        avatar: 'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/campana6.png',
        cargo: 'Desarrollador Frontend',
        nombre: 'Juan',
        apellido: 'Pérez',
        trabajando: true,
        email: 'jorge@gmail.com',
        empresa: 'Roudev',
        telefono: '123456789',
        siguiendo: false,
        proyectos: ['Proyecto 1', 'Proyecto 2'],
    },
    {
        id: '8',
        avatar: 'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/cloudflare.png',
        cargo: 'Desarrollador Frontend',
        nombre: 'Juan',
        apellido: 'Pérez',
        trabajando: true,
        email: 'jorge@gmail.com',
        empresa: 'Roudev',
        telefono: '123456789',
        siguiendo: false,
        proyectos: ['Proyecto 1', 'Proyecto 2'],
    },
    {
        id: '9',
        avatar: 'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/react.png',
        cargo: 'Desarrollador Frontend',
        nombre: 'Juan',
        apellido: 'Pérez',
        trabajando: true,
        email: 'jorge@gmail.com',
        empresa: 'Roudev',
        telefono: '123456789',
        siguiendo: false,
        proyectos: ['Proyecto 1', 'Proyecto 2'],
    },
    {
        id: '10',
        avatar: 'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/angular.png',
        cargo: 'Desarrollador Frontend',
        nombre: 'Juan',
        apellido: 'Pérez',
        trabajando: true,
        email: 'jorge@gmail.com',
        empresa: 'Roudev',
        telefono: '123456789',
        siguiendo: false,
        proyectos: [],
    },
    {
        id: '11',
        avatar: 'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/js.png',
        cargo: 'Desarrollador Frontend',
        nombre: 'Juan',
        apellido: 'Pérez',
        trabajando: true,
        email: 'jorge@gmail.com',
        empresa: 'Roudev',
        telefono: '123456789',
        siguiendo: false,
        proyectos: ['Proyecto 1', 'Proyecto 2', 'Proyecto 3'],
    },
    {
        id: '12',
        avatar: 'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/py.png',
        cargo: 'Desarrollador Frontend',
        nombre: 'Juan',
        apellido: 'Pérez',
        trabajando: true,
        email: 'jorge@gmail.com',
        empresa: 'Roudev',
        telefono: '123456789',
        siguiendo: false,
        proyectos: ['Proyecto 1', 'Proyecto 2'],
    },


]