

export const dataEmpleados =[
    {
        id:'1',
        avatar: 'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/aws.png',
        nombre: 'Juan',
        apellido: 'Pérez',
        cargo: 'SysAdmin',
        equipo: 'A',
        area: 'Infraestructura',
        fechaIngreso: '01-01-2023',
        status: 'Activo',
        email: 'juan@gmail.com',
    },
    {
        id:'2',
        avatar: 'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/azure.png',
        nombre: 'Juan',
        apellido: 'Pérez',
        cargo: 'Desarrollador',
        equipo: 'A',
        area: 'Desarrollo',
        fechaIngreso: '01-01-2023',
        status: 'Activo',
        email: 'juan@gmail.com',
    },
    {
        id:'3',
        avatar: 'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/cloudflare.png',
        nombre: 'Juan',
        apellido: 'Pérez',
        cargo: 'Diseño UX',
        equipo: 'A',
        area: 'Diseño',
        fechaIngreso: '01-01-2023',
        status: 'Activo',
        email: 'juan@gmail.com',
    },
    {
        id:'4',
        avatar: 'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/mas.png',
        nombre: 'Juan',
        apellido: 'Pérez',
        cargo: 'Desarrollador',
        equipo: 'A',
        area: 'Desarrollo',
        fechaIngreso: '01-01-2023',
        status: 'Activo',
        email: 'juan@gmail.com',
    },
    {
        id:'5',
        avatar: 'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/comida.png',
        nombre: 'Juan',
        apellido: 'Pérez',
        cargo: 'Database',
        equipo: 'A',
        area: 'Database',
        fechaIngreso: '01-01-2023',
        status: 'Activo',
        email: 'juan@gmail.com',
    },
] 