

export const dataTablaHome = [
    {
        id:'1',
        nombrePendiente: 'yarea 1',
        nombreEquipo: 'D',
        nombreCreador: 'Pedro Torres',
        nombreResponsable: 'Juan Lopez',
        colaboradores: ['juan', '', '', '', '', '', ''],
        status: 'Product Backlog',
        urgencia: 'Baja',
        fechaInicio: '29 abr',
        fechaFin: '8 may',
        estado: '-',
        etapa: 'Product Backlog'
    },
    {
        id:'2',
        nombrePendiente: 'Tareaddddddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxddcccccccccccdddd 2',
        nombreEquipo: 'C',
        nombreCreador: 'Pedro Torres',
        nombreResponsable: 'Marta Rivas',
        colaboradores: ['juan', 'Pedro', '', ''],
        status: 'Diseño UX / UI',
        urgencia: 'Alta',
        fechaInicio: '10 abr',
        fechaFin: '7 may',
        estado: 'Aportando',
        etapa: 'Product Backlog'

    },
    {
        id:'3',
        nombrePendiente: 'Taxxxxxxxxxxxxxxx433xbbbbbbbbbbbbbbbbbggrea 3',
        nombreEquipo: 'D',
        nombreCreador: 'Pedro Torres',
        nombreResponsable: 'Roberto Donoso',
        colaboradores: ['juan', 'Pedro'],
        status: 'QA',
        urgencia: 'Media',
        fechaInicio: '10 abr',
        fechaFin: '5 may',
        estado: '-',
        etapa: 'Desarrollo'
    },
    {
        id:'4',
        nombrePendiente: 'Tarea 4',
        nombreEquipo: 'A',
        nombreCreador: 'Pedro Torres',
        nombreResponsable: 'Marcos Morales',
        colaboradores: ['juan', 'Pedro', ''],
        status: 'Desarrollo',
        urgencia: 'Alta',
        fechaInicio: '10 abr',
        fechaFin: '4 may',
        estado: 'Pendiente de Aprobación',
        etapa: 'Debugger'
    },
    {
        id:'5',
        nombrePendiente: 'Tarea 5',
        nombreEquipo: 'C',
        nombreCreador: 'Pedro Torres',
        nombreResponsable: 'Marcos Morales',
        colaboradores: ['Juan', 'Pedro','Jorge', 'Pablo','Luis'],
        status: 'Produccion',
        urgencia: 'Baja',
        fechaInicio: '10 abr',
        fechaFin: '28 abr',
        estado: 'Aportando',
        etapa: 'Diseño'
    },
    // {
    //     id:'6',
    //     nombrePendiente: 'Tarea 6',
    //     nombreEquipo: 'B',
    //     nombreCreador: 'Pedro Torres',
    //     nombreResponsable: 'Marcos Morales',
    //     colaboradores: ['juan', 'Pedro'],
    //     status: 'Produccion',
    //     urgencia: 'Baja',
    //     fechaInicio: '10 abr',
    //     fechaFin: '28 abr',
    //     estado: 'Aportando',
    //     etapa: 'Produccion'
    // },
    // {
    //     id:'7',
    //     nombrePendiente: 'Tarea 7',
    //     nombreEquipo: 'A',
    //     nombreCreador: 'Pedro Torres',
    //     nombreResponsable: 'Marcos Morales',
    //     colaboradores: ['juan', 'Pedro', '', '', '', '', ''],
    //     status: 'Desarrollo',
    //     urgencia: 'Alta',
    //     fechaInicio: '10 abr',
    //     fechaFin: '4 may',
    //     estado: 'Pendiente de Aprobación',
    //     etapa: 'Produccion'
    // },
    // {
    //     id:'8',
    //     nombrePendiente: 'Tarea 8',
    //     nombreEquipo: 'C',
    //     nombreCreador: 'Pedro Torres',
    //     nombreResponsable: 'Marcos Morales',
    //     colaboradores: ['juan', 'Pedro', ''],
    //     status: 'Produccion',
    //     urgencia: 'Media',
    //     fechaInicio: '10 abr',
    //     fechaFin: '28 abr',
    //     estado: 'Aportando',
    //     etapa: 'Diseño'
    // },
    // {
    //     id:'9',
    //     nombrePendiente: 'Tarea 9',
    //     nombreEquipo: 'B',
    //     nombreCreador: 'Pedro Torres',
    //     nombreResponsable: 'Marcos Morales',
    //     colaboradores: ['juan', 'Pedro', '', '', ''],
    //     status: 'Produccion',
    //     urgencia: 'Baja',
    //     fechaInicio: '10 abr',
    //     fechaFin: '28 abr',
    //     estado: 'Aportando',
    //     etapa: 'Debugger'
    // },
    // {
    //     id:'10',
    //     nombrePendiente: 'Tarea 10',
    //     nombreEquipo: 'C',
    //     nombreCreador: 'Pedro Torres',
    //     nombreResponsable: 'Marcos Morales',
    //     colaboradores: ['juan', 'Pedro', ''],
    //     status: 'Produccion',
    //     urgencia: 'Baja',
    //     fechaInicio: '10 abr',
    //     fechaFin: '28 abr',
    //     estado: 'Aportando',
    //     etapa: 'Diseño'
    // },
    // {
    //     id:'11',
    //     nombrePendiente: 'Tarea 11',
    //     nombreEquipo: 'B',
    //     nombreCreador: 'Pedro Torres',
    //     nombreResponsable: 'Marcos Morales',
    //     colaboradores: ['juan', 'Pedro', '', '', '', '', '', '', ''],
    //     status: 'Produccion',
    //     urgencia: 'Media',
    //     fechaInicio: '10 abr',
    //     fechaFin: '28 abr',
    //     estado: 'Aportando',
    //     etapa: 'Desarrollo'
    // },
    // {
    //     id:'12',
    //     nombrePendiente: 'Tarea 12',
    //     nombreEquipo: 'A',
    //     nombreCreador: 'Pedro Torres',
    //     nombreResponsable: 'Marcos Morales',
    //     colaboradores: ['juan', 'Pedro'],
    //     status: 'Desarrollo',
    //     urgencia: 'Alta',
    //     fechaInicio: '10 abr',
    //     fechaFin: '4 may',
    //     estado: 'Pendiente de Aprobación',
    //     etapa: 'Debugger'
    // },
    // {
    //     id:'13',
    //     nombrePendiente: 'Tarea 13',
    //     nombreEquipo: 'C',
    //     nombreCreador: 'Pedro Torres',
    //     nombreResponsable: 'Marcos Morales',
    //     colaboradores: ['juan', 'Pedro'],
    //     status: 'Produccion',
    //     urgencia: 'Media',
    //     fechaInicio: '10 abr',
    //     fechaFin: '28 abr',
    //     estado: 'Aportando',
    //     etapa: 'QA'
    // },
    // {
    //     id:'14',
    //     nombrePendiente: 'Tarea 14',
    //     nombreEquipo: 'B',
    //     nombreCreador: 'Pedro Torres',
    //     nombreResponsable: 'Marcos Morales',
    //     colaboradores: ['juan', 'Pedro'],
    //     status: 'Produccion',
    //     urgencia: 'Alta',
    //     fechaInicio: '10 abr',
    //     fechaFin: '28 abr',
    //     estado: 'Aportando',
    //     etapa: 'Desarrollo'
    // },

    // {
    //     id:'15',
    //     nombrePendiente: 'Tarea 15',
    //     nombreEquipo: 'B',
    //     nombreCreador: 'Pedro Torres',
    //     nombreResponsable: 'Marcos Morales',
    //     colaboradores: ['juan', 'Pedro'],
    //     status: 'Produccion',
    //     urgencia: 'Baja',
    //     fechaInicio: '10 abr',
    //     fechaFin: '28 abr',
    //     estado: 'Aportando',
    //     etapa: 'Debugger'
    // },
    // {
    //     id:'16',
    //     nombrePendiente: 'Tarea 16',
    //     nombreEquipo: 'A',
    //     nombreCreador: 'Pedro Torres',
    //     nombreResponsable: 'Marcos Morales',
    //     colaboradores: [],
    //     status: 'Desarrollo',
    //     urgencia: 'Alta',
    //     fechaInicio: '10 abr',
    //     fechaFin: '4 may',
    //     estado: 'Pendiente de Aprobación',
    //     etapa: 'Product Backlog'
    // },
    // {
    //     id:'17',
    //     nombrePendiente: 'Tarea 17',
    //     nombreEquipo: 'C',
    //     nombreCreador: 'Pedro Torres',
    //     nombreResponsable: 'Marcos Morales',
    //     colaboradores: ['juan', 'Pedro'],
    //     status: 'Produccion',
    //     urgencia: 'Alta',
    //     fechaInicio: '10 abr',
    //     fechaFin: '28 abr',
    //     estado: 'Aportando',
    //     etapa: 'QA'
    // },
    // {
    //     id:'18',
    //     nombrePendiente: 'Tarea 18',
    //     nombreEquipo: 'B',
    //     nombreCreador: 'Pedro Torres',
    //     nombreResponsable: 'Marcos Morales',
    //     colaboradores: ['juan', 'Pedro'],
    //     status: 'Produccion',
    //     urgencia: 'Alta',
    //     fechaInicio: '10 abr',
    //     fechaFin: '28 abr',
    //     estado: 'Aportando',
    //     etapa: 'Produccion'
    // },
    // {
    //     id:'19',
    //     nombrePendiente: 'Tarea 19',
    //     nombreEquipo: 'C',
    //     nombreCreador: 'Pedro Torres',
    //     nombreResponsable: 'Marcos Morales',
    //     colaboradores: ['juan', 'Pedro'],
    //     status: 'Produccion',
    //     urgencia: 'Baja',
    //     fechaInicio: '10 abr',
    //     fechaFin: '28 abr',
    //     estado: 'Aportando',
    //     etapa: 'Product Backlog'
    // },
    // {
    //     id:'20',
    //     nombrePendiente: 'Tarea 20',
    //     nombreEquipo: 'A',
    //     nombreCreador: 'Pedro Torres',
    //     nombreResponsable: 'Marcos Morales',
    //     colaboradores: ['juan', 'Pedro'],
    //     status: 'Produccion',
    //     urgencia: 'Media',
    //     fechaInicio: '10 abr',
    //     fechaFin: '28 abr',
    //     estado: 'Aportando',
    //     etapa: 'Debugger'
    // },
    // {
    //     id:'21',
    //     nombrePendiente: 'Tarea 21',
    //     nombreEquipo: 'A',
    //     nombreCreador: 'Pedro Torres',
    //     nombreResponsable: 'Marcos Morales',
    //     colaboradores: ['juan', 'Pedro'],
    //     status: 'Desarrollo',
    //     urgencia: 'Baja',
    //     fechaInicio: '10 abr',
    //     fechaFin: '4 may',
    //     estado: 'Pendiente de Aprobación',
    //     etapa: 'Produccion'
    // },
    // {
    //     id:'22',
    //     nombrePendiente: 'Tarea 22',
    //     nombreEquipo: 'C',
    //     nombreCreador: 'Pedro Torres',
    //     nombreResponsable: 'Marcos Morales',
    //     colaboradores: ['juan', 'Pedro'],
    //     status: 'Produccion',
    //     urgencia: 'Baja',
    //     fechaInicio: '10 abr',
    //     fechaFin: '28 abr',
    //     estado: 'Aportando',
    //     etapa: 'QA'
    // },
    // {
    //     id:'23',
    //     nombrePendiente: 'Tarea 23',
    //     nombreEquipo: 'A',
    //     nombreCreador: 'Pedro Torres',
    //     nombreResponsable: 'Marcos Morales',
    //     colaboradores: ['juan', 'Pedro'],
    //     status: 'Produccion',
    //     urgencia: 'Alta',
    //     fechaInicio: '10 abr',
    //     fechaFin: '28 abr',
    //     estado: 'Aportando',
    //     etapa: 'Desarrollo'
    // },
    // {
    //     id:'24',
    //     nombrePendiente: 'Tarea 24',
    //     nombreEquipo: 'B',
    //     nombreCreador: 'Pedro Torres',
    //     nombreResponsable: 'Marcos Morales',
    //     colaboradores: ['juan', 'Pedro'],
    //     status: 'Produccion',
    //     urgencia: 'Media',
    //     fechaInicio: '10 abr',
    //     fechaFin: '28 abr',
    //     estado: 'Aportando',
    //     etapa: 'Product Backlog'
    // },
    // {
    //     id:'25',
    //     nombrePendiente: 'Tarea 25',
    //     nombreEquipo: 'B',
    //     nombreCreador: 'Pedro Torres',
    //     nombreResponsable: 'Marcos Morales',
    //     colaboradores: ['juan', 'Pedro'],
    //     status: 'Produccion',
    //     urgencia: 'Alta',
    //     fechaInicio: '10 abr',
    //     fechaFin: '28 abr',
    //     estado: 'Aportando',
    //     etapa: 'Product Backlog'
    // },
    // {
    //     id:'5',
    //     nombrePendiente: 'Tarea 5',
    //     nombreEquipo: 'Equipo A',s
    //     nombreResponsable: 'Juan Lopez',
    //     status: 'Pendiente',
    // },
    // {
    //     id:'6',
    //     nombrePendiente: 'Tarea 6',
    //     nombreEquipo: 'Equipo C',
    //     nombreResponsable: 'Marta Rivas',
    //     status: 'Pendiente',
    // },
    // {
    //     id:'7',
    //     nombrePendiente: 'Tarea 7',
    //     nombreEquipo: 'Equipo D',
    //     nombreResponsable: 'Roberto Donoso',
    //     status: 'Pendiente',
    // },
    // {
    //     id:'8',
    //     nombrePendiente: 'Tarea 8',
    //     nombreEquipo: 'Equipo A',
    //     nombreResponsable: 'Marcos Morales',
    //     status: 'Pendiente',
    // },
    // {
    //     id:'9',
    //     nombrePendiente: 'Tarea 5',
    //     nombreEquipo: 'Equipo A',
    //     nombreResponsable: 'Juan Lopez',
    //     status: 'Pendiente',
    // },
    // {
    //     id:'10',
    //     nombrePendiente: 'Tarea 6',
    //     nombreEquipo: 'Equipo C',
    //     nombreResponsable: 'Marta Rivas',
    //     status: 'Pendiente',
    // },
    // {
    //     id:'11',
    //     nombrePendiente: 'Tarea 7',
    //     nombreEquipo: 'Equipo D',
    //     nombreResponsable: 'Roberto Donoso',
    //     status: 'Pendiente',
    // },
    // {
    //     id:'12',
    //     nombrePendiente: 'Tarea 8',
    //     nombreEquipo: 'Equipo A',
    //     nombreResponsable: 'Marcos Morales',
    //     status: 'Pendiente',
    // },

]