

export const dataFounders =[
    {
        id:'1',
        avatar: 'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/aws.png',
        nombre: 'Juan',
        apellido: 'Pérez',
        cargo: 'CEO',
        equity: '50%',
        fechaIngreso: '01-01-2023',
        status: 'Activo',
        email: 'juan@gmail.com',
    },
    {
        id:'2',
        avatar: 'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/azure.png',
        nombre: 'Luis',
        apellido: 'Gomez',
        cargo: 'CTO',
        equity: '50%',
        fechaIngreso: '01-01-2023',
        status: 'Activo',
        email: 'luis@gmail.com',
    },
    // {
    //     id:'3',
    //     avatar: 'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/logoHistoriaREtornada.png',
    //     nombre: 'Juan',
    //     apellido: 'Pérez',
    //     cargo: 'CEO',
    //     equity: '50%',
    //     fechaIngreso: '01-01-2023',
    //     status: 'Activo',
    //     email: 'juan@gmail.com',
    // },
    // {
    //     id:'4',
    //     avatar: 'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/logoHistoriaREtornada.png',
    //     nombre: 'Juan',
    //     apellido: 'Pérez',
    //     cargo: 'CEO',
    //     equity: '50%',
    //     fechaIngreso: '01-01-2023',
    //     status: 'Activo',
    //     email: 'juan@gmail.com',
    // },
    // {
    //     id:'5',
    //     avatar: 'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/gcp.png',
    //     nombre: 'Juan',
    //     apellido: 'Pérez',
    //     cargo: 'CEO',
    //     equity: '50%',
    //     fechaIngreso: '01-01-2023',
    //     status: 'Activo',
    //     email: 'juan@gmail.com',
    // },

]