//import { avatar } from "@material-tailwind/react";

export const dataContactosStartUps = [
    {
        id:'1',
        avatar:'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/aws.png',
        nombre:'Pedro',
        apellido:'Lopez',
        cargo:'Desarrollador Backend',
        trabajando: true,
        email:'juan@gmail.com',
        tipoTrabajo: 'Presencial',
        experiencia: '2 años',
        fechaDisponibilidad: '01/01/2024',
        siguiendo: true,
        proyecto: ['Proyecto 1', 'Proyecto 2', 'Proyecto 3'],
        tipoEmpleo: 'Full Time',
        tipoEmpresa: 'Startup',
        salario: '3000 - 5000 USD',
    },
    {
        id:'2',
        avatar:'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/azure.png',
        nombre:'Luis',
        apellido:'Alvarez',
        cargo:'Desarrollador Backend',
        trabajando: true,
        email:'juan@gmail.com',
        tipoTrabajo: 'Presencial',
        experiencia: '2 años',
        fechaDisponibilidad: '01/01/2024',
        siguiendo: false,
        proyecto: [],
        tipoEmpleo: 'Full Time',
        tipoEmpresa: 'Startup',
        salario: '3000 - 5000 USD',
    },
    {
        id:'3',
        avatar:'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/comida.png',
        nombre:'Martina',
        apellido:'Benitez',
        cargo:'Desarrollador Backend',
        trabajando: false,
        email:'juan@gmail.com',
        tipoTrabajo: 'Presencial',
        experiencia: '2 años',
        fechaDisponibilidad: '01/01/2024',
        siguiendo: false,
        proyecto: ['Proyecto 1', 'Proyecto 2', 'Proyecto 3'],
        tipoEmpleo: 'Full Time',
        tipoEmpresa: 'Startup',
        salario: '3000 - 5000 USD',
    },
    {
        id:'4',
        avatar:'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/pregunta.png',
        nombre:'Camila',
        apellido:'Delgado',
        cargo:'Desarrollador Backend',
        trabajando: true,
        email:'juan@gmail.com',
        tipoTrabajo: 'Presencial',
        experiencia: '2 años',
        fechaDisponibilidad: '01/01/2024',
        siguiendo: true,
        proyecto: ['Proyecto 1', 'Proyecto 2', 'Proyecto 3', 'Proyecto 4'],
        tipoEmpleo: 'Full Time',
        tipoEmpresa: 'Startup',
        salario: '3000 - 5000 USD',
    },
    {
        id:'5',
        avatar:'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/check.png',
        nombre:'Romina',
        apellido:'Fernandez',
        cargo:'Desarrollador Backend',
        trabajando: false,
        email:'juan@gmail.com',
        tipoTrabajo: 'Presencial',
        experiencia: '2 años',
        fechaDisponibilidad: '01/01/2024',
        siguiendo: false,
        proyecto: [],
        tipoEmpleo: 'Full Time',
        tipoEmpresa: 'Startup',
        salario: '3000 - 5000 USD',
    },
    {
        id:'6',
        avatar:'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/campana2.png',
        nombre:'Oscar',
        apellido:'Gonzalez',
        cargo:'Desarrollador Backend',
        trabajando: true,
        email:'juan@gmail.com',
        tipoTrabajo: 'Presencial',
        experiencia: '2 años',
        fechaDisponibilidad: '01/01/2024',
        siguiendo: true,
        proyecto: ['Proyecto 1', 'Proyecto 2'],
        tipoEmpleo: 'Full Time',
        tipoEmpresa: 'Startup',
        salario: '3000 - 5000 USD',
    },
    {
        id:'7',
        avatar:'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/campana3.png',
        nombre:'Alba',
        apellido:'Hernandez',
        cargo:'Desarrollador Backend',
        trabajando: true,
        email:'juan@gmail.com',
        tipoTrabajo: 'Presencial',
        experiencia: '2 años',
        fechaDisponibilidad: '01/01/2024',
        siguiendo: true,
        proyecto: [],
        tipoEmpleo: 'Full Time',
        tipoEmpresa: 'Startup',
        salario: '3000 - 5000 USD',
    },
    {
        id:'8',
        avatar:'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/telefono3.png',
        nombre:'Bruno',
        apellido:'Martinez',
        cargo:'Desarrollador Backend',
        trabajando: false,
        email:'juan@gmail.com',
        tipoTrabajo: 'Presencial',
        experiencia: '2 años',
        fechaDisponibilidad: 'Inmediata',
        siguiendo: false,
        proyecto: ['Proyecto 1', 'Proyecto 2', 'Proyecto 3'],
        tipoEmpleo: 'Full Time',
        tipoEmpresa: 'Startup',
        salario: '3000 - 5000 USD',
    },
    {
        id:'9',
        avatar:'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/check.png',
        nombre:'Nombre',
        apellido:'Apellido',
        cargo:'Cargo',
        trabajando: true,
        email:'Email',
        tipoTrabajo: 'Presencial',
        experiencia: '2 años',
        fechaDisponibilidad: '01/01/2024',
        siguiendo: false,
        proyecto: ['Proyecto 1', 'Proyecto 2', 'Proyecto 3'],
        tipoEmpleo: 'Full Time',
        tipoEmpresa: 'Startup',
        salario: '3000 - 5000 USD',
    },
    {
        id:'10',
        avatar:'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/pregunta.png',
        nombre:'Nombre',
        apellido:'Apellido',
        cargo:'Cargo',
        trabajando: false,
        email:'Email',
        tipoTrabajo: 'Presencial',
        experiencia: '2 años',
        fechaDisponibilidad: '01/01/2024',
        siguiendo: false,
        proyecto: ['Proyecto 1', 'Proyecto 2', 'Proyecto 3'],
        tipoEmpleo: 'Full Time',
        tipoEmpresa: 'Startup',
        salario: '3000 - 5000 USD',
    },
    {
        id:'11',
        avatar:'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/angular.png',
        nombre:'Nombre',
        apellido:'Apellido',
        cargo:'Cargo',
        trabajando: true,
        email:'Email',
        tipoTrabajo: 'Presencial',
        experiencia: '2 años',
        fechaDisponibilidad: '01/01/2024',
        siguiendo: false,
        proyecto: ['Proyecto 1', 'Proyecto 2', 'Proyecto 3'],
        tipoEmpleo: 'Full Time',
        tipoEmpresa: 'Startup',
        salario: '3000 - 5000 USD',
    },
    {
        id:'12',
        avatar:'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/react.png',
        nombre:'Nombre',
        apellido:'Apellido',
        cargo:'Cargo',
        trabajando: true,
        email:'Email',
        tipoTrabajo: 'Presencial',
        experiencia: '2 años',
        fechaDisponibilidad: '01/01/2024',
        siguiendo: false,
        proyecto: ['Proyecto 1', 'Proyecto 2', 'Proyecto 3'],
        tipoEmpleo: 'Full Time',
        tipoEmpresa: 'Startup',
        salario: '3000 - 5000 USD',
    },
    {
        id:'13',
        avatar:'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/cloudflare.png',
        nombre:'Nombre',
        apellido:'Apellido',
        cargo:'Cargo',
        trabajando: false,
        email:'Email',
        tipoTrabajo: 'Presencial',
        experiencia: '2 años',
        fechaDisponibilidad: '01/01/2024',
        siguiendo: false,
        proyecto: ['Proyecto 1', 'Proyecto 2', 'Proyecto 3'],
        tipoEmpleo: 'Full Time',
        tipoEmpresa: 'Startup',
        salario: '3000 - 5000 USD',
    },
    {
        id:'14',
        avatar:'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/mysql.png',
        nombre:'Nombre',
        apellido:'Apellido',
        cargo:'Cargo',
        trabajando: true,
        email:'Email',
        tipoTrabajo: 'Presencial',
        experiencia: '2 años',
        fechaDisponibilidad: '01/01/2024',
        siguiendo: false,
        proyecto: ['Proyecto 1', 'Proyecto 2', 'Proyecto 3'],
        tipoEmpleo: 'Full Time',
        tipoEmpresa: 'Startup',
        salario: '3000 - 5000 USD',
    },
    {
        id:'15',
        avatar:'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/angular.png',
        nombre:'Nombre',
        apellido:'Apellido',
        cargo:'Cargo',
        trabajando: false,
        email:'Email',
        tipoTrabajo: 'Presencial',
        experiencia: '2 años',
        fechaDisponibilidad: '01/01/2024',
        siguiendo: false,
        proyecto: ['Proyecto 1', 'Proyecto 2', 'Proyecto 3'],
        tipoEmpleo: 'Full Time',
        tipoEmpresa: 'Startup',
        salario: '3000 - 5000 USD',
    },
    {
        id:'16',
        avatar:'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/vue.png',
        nombre:'Nombre',
        apellido:'Apellido',
        cargo:'Cargo',
        trabajando: true,
        email:'Email',
        tipoTrabajo: 'Presencial',
        experiencia: '2 años',
        fechaDisponibilidad: '01/01/2024',
        siguiendo: false,
        proyecto: ['Proyecto 1', 'Proyecto 2', 'Proyecto 3'],
        tipoEmpleo: 'Full Time',
        tipoEmpresa: 'Startup',
        salario: '3000 - 5000 USD',
    },
    {
        id:'17',
        avatar:'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/svelte.png',
        nombre:'Nombre',
        apellido:'Apellido',
        cargo:'Cargo',
        trabajando: true,
        email:'Email',
        tipoTrabajo: 'Presencial',
        experiencia: '2 años',
        fechaDisponibilidad: '01/01/2024',
        siguiendo: false,
        proyecto: ['Proyecto 1', 'Proyecto 2', 'Proyecto 3'],
        tipoEmpleo: 'Full Time',
        tipoEmpresa: 'Startup',
        salario: '3000 - 5000 USD',
    },
    {
        id:'18',
        avatar:'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/angular.png',
        nombre:'Nombre',
        apellido:'Apellido',
        cargo:'Cargo',
        trabajando: false,
        email:'Email',
        tipoTrabajo: 'Presencial',
        experiencia: '2 años',
        fechaDisponibilidad: '01/01/2024',
        siguiendo: false,
        proyecto: ['Proyecto 1', 'Proyecto 2', 'Proyecto 3'],
        tipoEmpleo: 'Full Time',
        tipoEmpresa: 'Startup',
        salario: '3000 - 5000 USD',
    },
    {
        id:'19',
        avatar:'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/react.png',
        nombre:'Nombre',
        apellido:'Apellido',
        cargo:'Cargo',
        trabajando: true,
        email:'Email',
        tipoTrabajo: 'Presencial',
        experiencia: '2 años',
        fechaDisponibilidad: '01/01/2024',
        siguiendo: false,
        proyecto: ['Proyecto 1', 'Proyecto 2', 'Proyecto 3'],
        tipoEmpleo: 'Full Time',
        tipoEmpresa: 'Startup',
        salario: '3000 - 5000 USD',
    },
    {
        id:'20',
        avatar:'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/nextjs.png',
        nombre:'Nombre',
        apellido:'Apellido',
        cargo:'Cargo',
        trabajando: false,
        email:'Email',
        tipoTrabajo: 'Presencial',
        experiencia: '2 años',
        fechaDisponibilidad: '01/01/2024',
        siguiendo: false,
        proyecto: ['Proyecto 1', 'Proyecto 2', 'Proyecto 3'],
        tipoEmpleo: 'Full Time',
        tipoEmpresa: 'Startup',
        salario: '3000 - 5000 USD',
    },
    {
        id:'21',
        avatar:'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/nestjs.png',
        nombre:'Nombre',
        apellido:'Apellido',
        cargo:'Cargo',
        trabajando: true,
        email:'Email',
        tipoTrabajo: 'Presencial',
        experiencia: '2 años',
        fechaDisponibilidad: '01/01/2024',
        siguiendo: false,
        proyecto: ['Proyecto 1', 'Proyecto 2', 'Proyecto 3'],
        tipoEmpleo: 'Full Time',
        tipoEmpresa: 'Startup',
        salario: '3000 - 5000 USD',
    },
    {
        id:'22',
        avatar:'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/react.png',
        nombre:'Nombre',
        apellido:'Apellido',
        cargo:'Cargo',
        trabajando: true,
        email:'Email',
        tipoTrabajo: 'Presencial',
        experiencia: '2 años',
        fechaDisponibilidad: '01/01/2024',
        siguiendo: false,
        proyecto: ['Proyecto 1', 'Proyecto 2', 'Proyecto 3'],
        tipoEmpleo: 'Full Time',
        tipoEmpresa: 'Startup',
        salario: '3000 - 5000 USD',
    },
    {
        id:'23',
        avatar:'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/angular.png',
        nombre:'Nombre',
        apellido:'Apellido',
        cargo:'Cargo',
        trabajando: false,
        email:'Email',
        tipoTrabajo: 'Presencial',
        experiencia: '2 años',
        fechaDisponibilidad: '01/01/2024',
        siguiendo: false,
        proyecto: ['Proyecto 1', 'Proyecto 2', 'Proyecto 3'],
        tipoEmpleo: 'Full Time',
        tipoEmpresa: 'Startup',
        salario: '3000 - 5000 USD',
    },
    {
        id:'24',
        avatar:'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/vue.png',
        nombre:'Nombre',
        apellido:'Apellido',
        cargo:'Cargo',
        trabajando: true,
        email:'Email',
        tipoTrabajo: 'Presencial',
        experiencia: '2 años',
        fechaDisponibilidad: '01/01/2024',
        siguiendo: false,
        proyecto: ['Proyecto 1', 'Proyecto 2', 'Proyecto 3'],
        tipoEmpleo: 'Full Time',
        tipoEmpresa: 'Startup',
        salario: '3000 - 5000 USD',
    },
    {
        id:'25',
        avatar:'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/home.png',
        nombre:'Nombre',
        apellido:'Apellido',
        cargo:'Cargo',
        trabajando: false,
        email:'Email',
        tipoTrabajo: 'Presencial',
        experiencia: '2 años',
        fechaDisponibilidad: '01/01/2024',
        siguiendo:true,
        proyecto: ['Proyecto 1', 'Proyecto 2', 'Proyecto 3'],
        tipoEmpleo: 'Full Time',
        tipoEmpresa: 'Startup',
        salario: '3000 - 5000 USD',
    },
    
]