

export const dataUnitsEconomics =[
    {
        id:'1',
        avatar: 'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/azure.png',
        nombre: 'Proyecto1',
        ingresos: 3100,
        runway: 10,
        dineroDisponible: 5000,
        lineaDeCredito: 7000,
        cac: 10,
        ltv: 21,
        churn: 3,
        status: 'Activo',
        
    },
    {
        id:'2',
        avatar: 'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/check.png',
        nombre: 'Proyecto2',
        ingresos: 3500,
        runway: 8,
        dineroDisponible: 5000,
        lineaDeCredito: 1000,
        cac: 12,
        ltv: 24,
        churn: 2,
        status: 'Activo',
        
    },
    {
        id:'3',
        avatar: 'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/aws.png',
        nombre: 'Proyecto3',
        ingresos: 3800,
        runway: 7,
        dineroDisponible: 5000,
        lineaDeCredito: 3000,
        cac: 12,
        ltv: 24,
        churn: 2,
        status: 'En Pausa',
        
    },
    // {
    //     id:'4',
    //     avatar: 'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/mas.png',
    //     nombre: 'Juan',
    //     apellido: 'Pérez',
    //     cargo: 'Desarrollador',
    //     equipo: 'A',
    //     area: 'Desarrollo',
    //     fechaIngreso: '01-01-2023',
    //     status: 'Activo',
    //     email: 'juan@gmail.com',
    // },
    // {
    //     id:'5',
    //     avatar: 'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/comida.png',
    //     nombre: 'Juan',
    //     apellido: 'Pérez',
    //     cargo: 'Database',
    //     equipo: 'A',
    //     area: 'Database',
    //     fechaIngreso: '01-01-2023',
    //     status: 'Activo',
    //     email: 'juan@gmail.com',
    // },
] 