

export const dataHistorialResolucionTarea = [
    {
        id:1,
        nombreTarea: 'uno',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
    {
        id:2,
        nombreTarea: 'dos',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
    {
        id:3,
        nombreTarea: 'tres',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
    {
        id:4,
        nombreTarea: 'cuatro',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
    {
        id:5,
        nombreTarea: 'uno',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
    {
        id:6,
        nombreTarea: 'dos',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
    {
        id:7,
        nombreTarea: 'tres',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
    {
        id:8,
        nombreTarea: 'cuatro',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
    {
        id:9,
        nombreTarea: 'uno',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
    {
        id:10,
        nombreTarea: 'dos',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
    {
        id:11,
        nombreTarea: 'tres',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
    {
        id:12,
        nombreTarea: 'cuatro',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
    {
        id:13,
        nombreTarea: 'uno',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
    {
        id:14,
        nombreTarea: 'dos',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
    {
        id:15,
        nombreTarea: 'tres',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
    {
        id:16,
        nombreTarea: 'cuatro',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
    {
        id:17,
        nombreTarea: 'uno',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
    {
        id:18,
        nombreTarea: 'dos',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
    {
        id:19,
        nombreTarea: 'tres',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
    {
        id:20,
        nombreTarea: 'cuatro',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
    {
        id:21,
        nombreTarea: 'uno',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
    {
        id:22,
        nombreTarea: 'dos',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
    {
        id:23,
        nombreTarea: 'tres',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
    {
        id:24,
        nombreTarea: 'cuatro',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
    {
        id:25,
        nombreTarea: 'uno',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
    {
        id:26,
        nombreTarea: 'dos',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
    {
        id:27,
        nombreTarea: 'tres',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
    {
        id:28,
        nombreTarea: 'cuatro',
        fechaIngreso: '12-12-2024',
        fechaRespuesta: '13-12-2024',
        status: 'Aceptada',
        discrepancia1: 'primera',
        discrepancia2: 'segunda',
        discrepancia3: 'tercera',
        discrepancia4: 'cuarta',
    },
]