


export const dataProductBacklogPo = [
    {
        id:1,
        nombreTarea: 'uno',
        areaSolicitante: 'Cliente',
        deptoSolicitante: 'Stake Holder',
        cargoSolicitante: 'Finanzas',
        nombreSolitante: 'Juan Perez',
        fechaDeSolicitud: '12-10-2024',
        horaDeSolicitud: '11:28',
        caracterDeSolicitud: 'Estructural',
        problemaDeSolicitud: 'Crecimiento',
        presupuestoDeSolicitud: '300.000',
        tiempoDeEjecucion: '7',
        status: 'En desarrollo',
        sprint: '11'
    },
    {
        id:2,
        nombreTarea: 'uno',
        areaSolicitante: 'Cliente',
        deptoSolicitante: 'Stake Holder',
        cargoSolicitante: 'Finanzas',
        nombreSolitante: 'Juan Perez',
        fechaDeSolicitud: '12-10-2024',
        horaDeSolicitud: '11:28',
        caracterDeSolicitud: 'Estructural',
        problemaDeSolicitud: 'Crecimiento',
        presupuestoDeSolicitud: '300.000',
        tiempoDeEjecucion: '7',
        status: 'Pendiente',
        sprint: '-'
    },
    {
        id:3,
        nombreTarea: 'uno',
        areaSolicitante: 'Cliente',
        deptoSolicitante: 'Stake Holder',
        cargoSolicitante: 'Finanzas',
        nombreSolitante: 'Juan Perez',
        fechaDeSolicitud: '12-10-2024',
        horaDeSolicitud: '11:28',
        caracterDeSolicitud: 'Estructural',
        problemaDeSolicitud: 'Crecimiento',
        presupuestoDeSolicitud: '300.000',
        tiempoDeEjecucion: '7',
        status: 'Pendiente',
        sprint: '-'
    },
    {
        id:4,
        nombreTarea: 'uno',
        areaSolicitante: 'Cliente',
        deptoSolicitante: 'Stake Holder',
        cargoSolicitante: 'Finanzas',
        nombreSolitante: 'Juan Perez',
        fechaDeSolicitud: '12-10-2024',
        horaDeSolicitud: '11:28',
        caracterDeSolicitud: 'Estructural',
        problemaDeSolicitud: 'Crecimiento',
        presupuestoDeSolicitud: '300.000',
        tiempoDeEjecucion: '7',
        status: 'Pendiente',
        sprint: '-'
    },
    {
        id:5,
        nombreTarea: 'uno',
        areaSolicitante: 'Cliente',
        deptoSolicitante: 'Stake Holder',
        cargoSolicitante: 'Finanzas',
        nombreSolitante: 'Juan Perez',
        fechaDeSolicitud: '12-10-2024',
        horaDeSolicitud: '11:28',
        caracterDeSolicitud: 'Estructural',
        problemaDeSolicitud: 'Crecimiento',
        presupuestoDeSolicitud: '300.000',
        tiempoDeEjecucion: '7',
        status: 'Pendiente',
        sprint: '-'
    },
    {
        id:6,
        nombreTarea: 'uno',
        areaSolicitante: 'Cliente',
        deptoSolicitante: 'Stake Holder',
        cargoSolicitante: 'Finanzas',
        nombreSolitante: 'Juan Perez',
        fechaDeSolicitud: '12-10-2024',
        horaDeSolicitud: '11:28',
        caracterDeSolicitud: 'Estructural',
        problemaDeSolicitud: 'Crecimiento',
        presupuestoDeSolicitud: '300.000',
        tiempoDeEjecucion: '7',
        status: 'Pendiente',
        sprint: '-'
    },
    {
        id:7,
        nombreTarea: 'uno',
        areaSolicitante: 'Cliente',
        deptoSolicitante: 'Stake Holder',
        cargoSolicitante: 'Finanzas',
        nombreSolitante: 'Juan Perez',
        fechaDeSolicitud: '12-10-2024',
        horaDeSolicitud: '11:28',
        caracterDeSolicitud: 'Estructural',
        problemaDeSolicitud: 'Crecimiento',
        presupuestoDeSolicitud: '300.000',
        tiempoDeEjecucion: '7',
        status: 'Pendiente',
        sprint: '-'
    },
    
]