

export const dataDevSprintBacklogHistorial = [
    {
        id:1,
        nSprint: '1',
        nSemanas: 2,
        fechaInicio: '12-10-2024',
        fechaTermino: '30-10-2024',
        tarea1: 'weas',
        tarea2: 'weas',
        tarea3: 'weas',
        tarea4: 'weas',
    },
    {
        id:2,
        nSprint: '1',
        nSemanas: 2,
        fechaInicio: '12-10-2024',
        fechaTermino: '30-10-2024',
        tarea1: 'weas',
        tarea2: 'weas',
        tarea3: 'weas',
        tarea4: 'weas',
    },
    {
        id:3,
        nSprint: '1',
        nSemanas: 2,
        fechaInicio: '12-10-2024',
        fechaTermino: '30-10-2024',
        tarea1: 'weas',
        tarea2: 'weas',
        tarea3: 'weas',
        tarea4: 'weas',
    },
    {
        id:4,
        nSprint: '1',
        nSemanas: 2,
        fechaInicio: '12-10-2024',
        fechaTermino: '30-10-2024',
        tarea1: 'weas',
        tarea2: 'weas',
        tarea3: 'weas',
        tarea4: 'weas',
    },
    {
        id:5,
        nSprint: '1',
        nSemanas: 2,
        fechaInicio: '12-10-2024',
        fechaTermino: '30-10-2024',
        tarea1: 'weas',
        tarea2: 'weas',
        tarea3: 'weas',
        tarea4: 'weas',
    },
    {
        id:6,
        nSprint: '1',
        nSemanas: 2,
        fechaInicio: '12-10-2024',
        fechaTermino: '30-10-2024',
        tarea1: 'weas',
        tarea2: 'weas',
        tarea3: 'weas',
        tarea4: 'weas',
    },

    {
        id:1,
        nSprint: '1',
        nSemanas: 2,
        fechaInicio: '12-10-2024',
        fechaTermino: '30-10-2024',
        tarea1: 'weas',
        tarea2: 'weas',
        tarea3: 'weas',
        tarea4: 'weas',
    },
    {
        id:2,
        nSprint: '1',
        nSemanas: 2,
        fechaInicio: '12-10-2024',
        fechaTermino: '30-10-2024',
        tarea1: 'weas',
        tarea2: 'weas',
        tarea3: 'weas',
        tarea4: 'weas',
    },
    {
        id:3,
        nSprint: '1',
        nSemanas: 2,
        fechaInicio: '12-10-2024',
        fechaTermino: '30-10-2024',
        tarea1: 'weas',
        tarea2: 'weas',
        tarea3: 'weas',
        tarea4: 'weas',
    },
    {
        id:4,
        nSprint: '1',
        nSemanas: 2,
        fechaInicio: '12-10-2024',
        fechaTermino: '30-10-2024',
        tarea1: 'weas',
        tarea2: 'weas',
        tarea3: 'weas',
        tarea4: 'weas',
    },
    {
        id:5,
        nSprint: '1',
        nSemanas: 2,
        fechaInicio: '12-10-2024',
        fechaTermino: '30-10-2024',
        tarea1: 'weas',
        tarea2: 'weas',
        tarea3: 'weas',
        tarea4: 'weas',
    },
    {
        id:6,
        nSprint: '1',
        nSemanas: 2,
        fechaInicio: '12-10-2024',
        fechaTermino: '30-10-2024',
        tarea1: 'weas',
        tarea2: 'weas',
        tarea3: 'weas',
        tarea4: 'weas',
    },

    {
        id:1,
        nSprint: '1',
        nSemanas: 2,
        fechaInicio: '12-10-2024',
        fechaTermino: '30-10-2024',
        tarea1: 'weas',
        tarea2: 'weas',
        tarea3: 'weas',
        tarea4: 'weas',
    },
    {
        id:2,
        nSprint: '1',
        nSemanas: 2,
        fechaInicio: '12-10-2024',
        fechaTermino: '30-10-2024',
        tarea1: 'weas',
        tarea2: 'weas',
        tarea3: 'weas',
        tarea4: 'weas',
    },
    {
        id:3,
        nSprint: '1',
        nSemanas: 2,
        fechaInicio: '12-10-2024',
        fechaTermino: '30-10-2024',
        tarea1: 'weas',
        tarea2: 'weas',
        tarea3: 'weas',
        tarea4: 'weas',
    },
    {
        id:4,
        nSprint: '1',
        nSemanas: 2,
        fechaInicio: '12-10-2024',
        fechaTermino: '30-10-2024',
        tarea1: 'weas',
        tarea2: 'weas',
        tarea3: 'weas',
        tarea4: 'weas',
    },
    {
        id:5,
        nSprint: '1',
        nSemanas: 2,
        fechaInicio: '12-10-2024',
        fechaTermino: '30-10-2024',
        tarea1: 'weas',
        tarea2: 'weas',
        tarea3: 'weas',
        tarea4: 'weas',
    },
    {
        id:6,
        nSprint: '1',
        nSemanas: 2,
        fechaInicio: '12-10-2024',
        fechaTermino: '30-10-2024',
        tarea1: 'weas',
        tarea2: 'weas',
        tarea3: 'weas',
        tarea4: 'weas',
    },
]